[project]
name = "hackaton"
version = "0.1.0"
description = "PubMed API Client"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.0",
    "asyncpg>=0.30.0",
    "biopython>=1.85",
    "crawl4ai>=0.7.6",
    "ddgs>=9.5.2",
    "fastapi>=0.119.1",
    "httpx>=0.28.1",
    "ipykernel>=7.0.1",
    "jinja2>=3.1.6",
    "langchain>=1.0.2",
    "langchain-community>=0.4",
    "langchain-openai>=1.0.1",
    "loguru>=0.7.3",
    "nebius>=0.3.2",
    "numpy>=2.3.4",
    "openai>=2.6.0",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.7",
    "pydantic-settings>=2.11.0",
    "redis[asyncio]>=7.0.0",
    "requests>=2.31.0",
    "sentence-transformers>=5.1.2",
    "sqlalchemy[asyncio]>=2.0.44",
    "uvicorn[standard]>=0.38.0",
]
