"""Add foreign key constraint to article_analyses

Revision ID: 3a97775e6845
Revises: 65c9283b2930
Create Date: 2025-10-22 20:15:13.192455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a97775e6845'
down_revision: Union[str, Sequence[str], None] = '65c9283b2930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article_analyses', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_analyses', type_='foreignkey')
    # ### end Alembic commands ###
