"""Add aging theories and article theories tables with analysis enhancements

Revision ID: 5066b257e5f1
Revises: 3a97775e6845
Create Date: 2025-10-22 20:34:22.512934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5066b257e5f1'
down_revision: Union[str, Sequence[str], None] = '3a97775e6845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create aging_theories table
    op.create_table('aging_theories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('theory_name', sa.String(length=500), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('evidence_level', sa.String(length=20), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('first_mentioned_in_article_id', sa.UUID(), nullable=True),
        sa.Column('mention_count', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['first_mentioned_in_article_id'], ['articles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_theory_name', 'aging_theories', ['theory_name'], unique=False)
    op.create_index('idx_theory_category', 'aging_theories', ['category'], unique=False)
    op.create_index('idx_theory_evidence_level', 'aging_theories', ['evidence_level'], unique=False)
    op.create_index(op.f('ix_aging_theories_theory_name'), 'aging_theories', ['theory_name'], unique=True)
    
    # Create article_theories table
    op.create_table('article_theories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('article_id', sa.UUID(), nullable=False),
        sa.Column('theory_id', sa.UUID(), nullable=False),
        sa.Column('relevance_score', sa.Float(), nullable=True),
        sa.Column('extracted_context', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
        sa.ForeignKeyConstraint(['theory_id'], ['aging_theories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_theory_article_id', 'article_theories', ['article_id'], unique=False)
    op.create_index('idx_article_theory_theory_id', 'article_theories', ['theory_id'], unique=False)
    op.create_index(op.f('ix_article_theories_article_id'), 'article_theories', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_theories_theory_id'), 'article_theories', ['theory_id'], unique=False)
    
    # Add columns to article_analyses
    op.add_column('article_analyses', sa.Column('review_summary', sa.Text(), nullable=True))
    op.add_column('article_analyses', sa.Column('citation_analysis', sa.JSON(), nullable=True))
    op.add_column('article_analyses', sa.Column('actuality_score', sa.Float(), nullable=True))
    op.add_column('article_analyses', sa.Column('controversy_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop columns from article_analyses
    op.drop_column('article_analyses', 'controversy_level')
    op.drop_column('article_analyses', 'actuality_score')
    op.drop_column('article_analyses', 'citation_analysis')
    op.drop_column('article_analyses', 'review_summary')
    
    # Drop article_theories table
    op.drop_index(op.f('ix_article_theories_theory_id'), table_name='article_theories')
    op.drop_index(op.f('ix_article_theories_article_id'), table_name='article_theories')
    op.drop_index('idx_article_theory_theory_id', table_name='article_theories')
    op.drop_index('idx_article_theory_article_id', table_name='article_theories')
    op.drop_table('article_theories')
    
    # Drop aging_theories table
    op.drop_index(op.f('ix_aging_theories_theory_name'), table_name='aging_theories')
    op.drop_index('idx_theory_evidence_level', table_name='aging_theories')
    op.drop_index('idx_theory_category', table_name='aging_theories')
    op.drop_index('idx_theory_name', table_name='aging_theories')
    op.drop_table('aging_theories')
    # ### end Alembic commands ###
