"""Initial schema with articles, analyses, and data sources

Revision ID: 65c9283b2930
Revises: 
Create Date: 2025-10-22 19:19:31.586090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c9283b2930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('q1_biomarker', sa.String(length=10), nullable=True),
    sa.Column('q1_explanation', sa.Text(), nullable=True),
    sa.Column('q2_molecular_mechanism', sa.String(length=10), nullable=True),
    sa.Column('q2_explanation', sa.Text(), nullable=True),
    sa.Column('q3_longevity_intervention', sa.String(length=10), nullable=True),
    sa.Column('q3_explanation', sa.Text(), nullable=True),
    sa.Column('q4_aging_irreversible', sa.String(length=10), nullable=True),
    sa.Column('q4_explanation', sa.Text(), nullable=True),
    sa.Column('q5_species_lifespan_biomarker', sa.String(length=10), nullable=True),
    sa.Column('q5_explanation', sa.Text(), nullable=True),
    sa.Column('q6_naked_mole_rat', sa.String(length=10), nullable=True),
    sa.Column('q6_explanation', sa.Text(), nullable=True),
    sa.Column('q7_bird_longevity', sa.String(length=10), nullable=True),
    sa.Column('q7_explanation', sa.Text(), nullable=True),
    sa.Column('q8_size_lifespan', sa.String(length=10), nullable=True),
    sa.Column('q8_explanation', sa.Text(), nullable=True),
    sa.Column('q9_calorie_restriction', sa.String(length=10), nullable=True),
    sa.Column('q9_explanation', sa.Text(), nullable=True),
    sa.Column('analysis_cost', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_analyzed_at', 'article_analyses', ['analyzed_at'], unique=False)
    op.create_index('idx_analysis_article_id', 'article_analyses', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_analyses_article_id'), 'article_analyses', ['article_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('full_text_url', sa.String(length=1000), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('is_aging_related', sa.Boolean(), nullable=False),
    sa.Column('classification_confidence', sa.String(length=20), nullable=True),
    sa.Column('classification_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_created_at', 'articles', ['created_at'], unique=False)
    op.create_index('idx_article_source', 'articles', ['source'], unique=False)
    op.create_index('idx_article_year', 'articles', ['year'], unique=False)
    op.create_index(op.f('ix_articles_doi'), 'articles', ['doi'], unique=True)
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('api_client_class', sa.String(length=200), nullable=True),
    sa.Column('user_api_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_index('idx_data_source_active', 'data_sources', ['is_active'], unique=False)
    op.create_index('idx_data_source_name', 'data_sources', ['source_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_data_source_name', table_name='data_sources')
    op.drop_index('idx_data_source_active', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_articles_doi'), table_name='articles')
    op.drop_index('idx_article_year', table_name='articles')
    op.drop_index('idx_article_source', table_name='articles')
    op.drop_index('idx_article_created_at', table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_article_analyses_article_id'), table_name='article_analyses')
    op.drop_index('idx_analysis_article_id', table_name='article_analyses')
    op.drop_index('idx_analysis_analyzed_at', table_name='article_analyses')
    op.drop_table('article_analyses')
    # ### end Alembic commands ###
