"""add_review_columns_to_analyses

Revision ID: db709a2dbde7
Revises: 5066b257e5f1
Create Date: 2025-10-22 23:55:54.525339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db709a2dbde7'
down_revision: Union[str, Sequence[str], None] = '5066b257e5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_analyses', sa.Column('review_summary', sa.Text(), nullable=True))
    op.add_column('article_analyses', sa.Column('citation_analysis', sa.JSON(), nullable=True))
    op.add_column('article_analyses', sa.Column('actuality_score', sa.Float(), nullable=True))
    op.add_column('article_analyses', sa.Column('controversy_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_analyses', 'controversy_level')
    op.drop_column('article_analyses', 'actuality_score')
    op.drop_column('article_analyses', 'citation_analysis')
    op.drop_column('article_analyses', 'review_summary')
    # ### end Alembic commands ###
